import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[font.normal]
# family = "JetBrainsMono Nerd Font Mono"
# family = "BerkeleyMono Nerd Font"
# family = "0xProto Nerd Font Mono"
family = "Hack Nerd Font Mono"
# family = "SpaceMono Nerd Font Mono"
style = "Regular"
# style = "Light"

[font]
size = 13

[env]
TERM = "xterm-256color"
